apiVersion: skaffold/v2beta5
kind: Config
build:
  local:
    push: true
    useDockerCLI: true
  artifacts:
    - image: gcr.io/thalescpl-io/k8s-kms-plugin/server
      docker:
        dockerfile: Dockerfile
        target: kms-server