#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: k8s-kms-plugin-client
##  namespace: kube-system
#  labels:
#    app.kubernetes.io/name: k8s-kms-plugin
#spec:
#  selector:
#    matchLabels:
#      app.kubernetes.io/name: k8s-kms-plugin
#
#  template:
#    metadata:
#      labels:
#        app.kubernetes.io/name: k8s-kms-plugin
#    spec:
#      volumes:
#        - name: kms-socket
#          hostPath:
#            path: /run/kms/kms-socket
#
#      containers:
#        - name: k8s-kms-plugin
#          image: "gcr.io/thalescpl-io/k8s-kms-plugin/client"
#          imagePullPolicy: IfNotPresent
#          args:
#            - enroll
#            - --host=k8s-kms-plugin-server
#            - -k
#            - -r
#          volumeMounts:
#            - mountPath: /run/kms/kms-socket
#              name: kms-socket