apiVersion: v1
kind: Pod
metadata:
  name: k8s-kms-plugin-server
  #  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8s-kms-plugin
spec:
  volumes:
    - name: certstore
      emptyDir: {}

    - name: ca
      hostPath:
        path: /etc/
  initContainers:
    - name: config
      image: "gcr.io/thalescpl-io/k8s-kms-plugin"
      volumeMounts:
        - mountPath: /certs/
          name: certstore
      args:
        - bootstrap
  containers:
    - name: k8s-kms-plugin
      image: "gcr.io/thalescpl-io/k8s-kms-plugin"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 31400
          protocol: TCP
          name: grpc
        - containerPort: 443
          protocol: TCP
          name: est
      livenessProbe:
        tcpSocket:
          port: 31400
      readinessProbe:
        tcpSocket:
          port: 443
      env:
        - name: P11_LIB
          value: /
      args:
        - serve